### ISSUE TITLE
Support shrinkwrap options

### ISSUE THREAD

**Issue by openjck** [chmontgomery/gulp-shrinkwrap#4]
It would be great if gulp-shrinkwrap supported passing options (like `--dev`) to shrinkwrap.

**Comment by chmontgomery** [comment]
a PR is welcome!

**Comment by chmontgomery** [comment]
@openjck can you try out `v2.0.0` and see if that fits your requirements? Thanks!

**Comment by openjck** [comment]
Looks awesome! This is exactly what I had in mind. I notice gulp-shrinkwrap excludes dependencies even when `devDependencies` is set to true. Maybe I'm reading the documentation wrong?

**Comment by chmontgomery** [comment]
I think what you're seeing is a difference between `shinkwrap.lock` and `shrinkwrap`? Lock takes `devDependencies` as an arg, while `shrinkwrap` accepts `dev`. Can you try this?:

```
gulp.task('shrinkwrap', function () {
  return gulp.src('package.json')
    .pipe(shrinkwrap({dev:true}))
    .pipe(gulp.dest('./'));
});
```

**Comment by openjck** [comment]
Ah, you're right. That works perfectly. Thanks Chris! :smile:
