### ISSUE TITLE
TypeError when running single task

### ISSUE THREAD

**Issue by NickyL** [chmontgomery/gulp-shrinkwrap#5]
I have a very simple gulp task setup to run like so:
```sh
gulp.task('shrinkwrap', function() {
    return gulp.src('package.json')
        .pipe(shrinkwrap())
        .pipe(gulp.dest('./'))
        .pipe(gutil.log(gutil.colors.green('Build Successful!')));
});
```

But when I run it, it keeps running into the same error. I'm assuming it's a bug, because I searched the internet for solutions, none found. Since this is the only plugin affected, I figured it's most likely a bug. However, it **does** write the actual ``npm-shrinkwrap.json`` file.

Bug in ternminal:
![gulp-shrinkwrap-bug](https://cloud.githubusercontent.com/assets/2785350/6539192/7f2c68be-c46e-11e4-919c-4f0a8b27ed9a.jpg)

You can ignore the 'Connected to MEAN Developer Database' in between.

**Comment by chmontgomery** [comment]
If you figure out a solution I would accept a pull request.

**Comment by NickyL** [comment]
I'm not too familiar with writing the actual plugins, but I'll keep an eye out!

**Comment by chmontgomery** [comment]
@NickyL can you try `v2.0.0` and see if that fixes your problem? Thanks!

**Comment by NickyL** [comment]
I'll give it a go tomorrow. I'll let you know!

**Comment by NickyL** [comment]
@chmontgomery I still get the exact same error after updating to ```v2.0.1```. Any ideas?

**Comment by chmontgomery** [comment]
can you paste in the contents of your `package.json`?

**Comment by NickyL** [comment]
```gulp v 3.8.11``` (both global and local)

My relevant ```package.json```:
```sh
"devDependencies": {
    "dedupe": "1.0.0",
    "gulp": "3.8.11",
    "gulp-angular-htmlify": "2.1.1",
    "gulp-autoprefixer": "2.0.0",
    "gulp-concat": "2.4.2",
    "gulp-if": "1.2.5",
    "gulp-imagemin": "^2.2.1",
    "gulp-jshint": "1.9.0",
    "gulp-livereload": "3.0.2",
    "gulp-minify-css": "0.5.1",
    "gulp-minify-html": "0.1.8",
    "gulp-plumber": "0.6.6",
    "gulp-processhtml": "1.0.2",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "1.3.3",
    "gulp-shrinkwrap": "^2.0.1",
    "gulp-sourcemaps": "1.5.0",
    "gulp-typescript": "2.4.2",
    "gulp-uglify": "1.0.2",
    "gulp-util": "3.0.1",
    "merge2": "^0.3.1",
    "morgan": "1.5.1",
    "node-sass": "2.0.1",
    "yargs": "1.3.3"
  },
  "dependencies": {
    "body-parser": "1.10.0",
    "express": "4.10.6",
    "mongoose": "3.8.23"
  }
```

**Comment by chmontgomery** [comment]
@NickyL Using your `package.json` and gulp task I'm seeing a different error message than you but I think it may be related:

```js
[22:13:22] Using gulpfile ~/Projects/test/1/gulpfile.js
[22:13:22] Starting 'shrinkwrap'...
[22:13:22] Build Successful!
[22:13:22] 'shrinkwrap' errored after 5.65 ms
[22:13:22] TypeError: Object #<Object> has no method 'on'
    at DestroyableTransform.Stream.pipe (stream.js:65:8)
    at Gulp.<anonymous> (/Users/montgomeryc/Projects/test/1/gulpfile.js:9:7)
    at module.exports (/Users/montgomeryc/Projects/test/1/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/montgomeryc/Projects/test/1/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/montgomeryc/Projects/test/1/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/montgomeryc/Projects/test/1/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/montgomeryc/.nvm/v0.10.33/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

The problem has to do with your `gulpfile.js`. `gutil.log` is not meant to be called as part of a stream. Either remove the pipe to `gutil` or use a package like through2 and put the call to gutil inside there. If you're still seeing an error message, make sure to start fresh by doing the following (assuming you're in a linux/unix env):

```bash
rm -r node_modules
npm cache clean
npm install
```
