### ISSUE TITLE
Update readme with shrinkwrap({dev:true})

### ISSUE THREAD

**Issue by dennismphil** [chmontgomery/gulp-shrinkwrap#8]
It would be great to see `shrinkwrap({dev:true})` in the documentation to know it supports shrinkwrap options. 

```
gulp.src("package.json")
    .pipe(shrinkwrap({dev:true}))
```

**Comment by chmontgomery** [comment]
I would accept a PR!

**Comment by caseyhoward** [comment]
This can probably be closed now.
